---

driver:
  name: docker

platforms:
  - name: aws_ec2_perf-trusty
    image: ubuntu:trusty
    privileged: yes
  - name: aws_ec2_perf-xenial
    image: ubuntu:xenial
    privileged: yes
  - name: aws_ec2_perf-bionic
    image: solita/ubuntu-systemd:bionic
    command: /sbin/init
    capabilities:
      - SYS_ADMIN
    privileged: yes
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

provisioner:
  name: ansible
  lint:
    name: ansible-lint

lint:
  name: yamllint
  options:
    config-data:
      extends: default
      ignore: .venv_ansible*
      rules:
        line-length:
          max: 159
        truthy: disable

dependency:
  name: galaxy

scenario:
  name: default

verifier:
  name: testinfra
  lint:
    name: flake8
